name: Build and Deploy to Azure Container Apps

on:
  push:
    tags:
      - "*"

env:
  AZURE_REGION: centralindia
  RESOURCE_GROUP: Titanium
  CONTAINER_APP_NAME: titanium
  TARGET_PORT: 3000

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # AUTH + CODE
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_GITHUB_ACTIONS }}

      # DEPLOY FROM SOURCE USING DOCKERFILE
      - name: Create/update Container App from Dockerfile
        run: |
          az containerapp up \
            --name "${{ env.CONTAINER_APP_NAME }}" \
            --resource-group "${{ env.RESOURCE_GROUP }}" \
            --location "${{ env.AZURE_REGION }}" \
            --source . \
            --target-port "${{ env.TARGET_PORT }}" \
            --ingress external \
            --env-vars \
              DATABASE_URL=${{ secrets.DATABASE_URL }} \
              DIRECT_URL=${{ secrets.DATABASE_URL }} \
              SERVER_URL=${{ secrets.DATABASE_URL }} \
              WEB_CLIENT_URL=${{ secrets. WEB_CLIENT_URL }} \
              BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}
